/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_esteban;

/**
 *
 * @author esteban
 */
public class Analizar extends javax.swing.JFrame {
    static TablaDeDispersion tabladd;
    static TablaPorPalabrasClave tablapc;
    /**
     * Creates new form Analizar
     */
    public Analizar(TablaDeDispersion tabladd, TablaPorPalabrasClave tablapc) {
        initComponents();
        this.tabladd = tabladd;
        this.tablapc = tablapc;
        for (int i = 0; i < 20; i++) {
            try{
                this.titulo.addItem(this.tabladd.articulos[i].getTitulo());
            }catch(Exception e){
//                e.printStackTrace();
            }
        }
//        for (int i = 0; i < tabladd.total; i++) {
//            try{
//                System.out.println(tabladd.articulos[i].getTitulo());
//            }catch(Exception e){
//                
//            }
//        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        analizar = new javax.swing.JButton();
        analizar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        titulo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        analisis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setText("Analisis:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        analizar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar.setForeground(new java.awt.Color(60, 63, 65));
        analizar.setText("ANALIZAR");
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });
        jPanel1.add(analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        analizar1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar1.setForeground(new java.awt.Color(60, 63, 65));
        analizar1.setText("SALIR");
        analizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizar1ActionPerformed(evt);
            }
        });
        jPanel1.add(analizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel2.setText("ANALIZAR RESUMEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        titulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 330, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel3.setText("Resumenes disponibles:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        analisis.setColumns(20);
        analisis.setRows(5);
        jScrollPane2.setViewportView(analisis);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 320, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizar1ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu(tabladd, tablapc);
        this.dispose();
    }//GEN-LAST:event_analizar1ActionPerformed

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed
        // TODO add your handling code here:
        this.analisis.setText(this.tabladd.busquedaPorTitulo(this.titulo.getSelectedItem().toString().toLowerCase()).analisis());
    }//GEN-LAST:event_analizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analizar(tabladd, tablapc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea analisis;
    private javax.swing.JButton analizar;
    private javax.swing.JButton analizar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> titulo;
    // End of variables declaration//GEN-END:variables
}
